### ISSUE TITLE
Allow for argument to validate or not

### ISSUE THREAD

**Issue by sondreb** [afizzycola/satcomma-js#8]
Hi! Would a PR with an additional argument overload after `delimiterForSats` that would enable or disable `checkMaxSatoshis` be approved? It would make the library useable for blockchains other than Bitcoin and it would solve #5 who is asking for negative value support. We're building tooling for Bitcoin and many other Bitcoin-protocol-based chains and need this additional feature. We can fork and make our own release if this library want to stay focused only on Bitcoin. Thanks!

**Comment by afizzycola** [comment]
Hi @sondreb. I think that would be a sensible addition to the library. Happy to look at the PR! Thanks
